// MeshIO.cs
// Mesh input/output utilities
// Added by Graph Technologies, 2025
// Description: Load and save meshes in OBJ and OFF formats

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Numerics;
using DDGCompanion.Core;

namespace DDGCompanion.Utils
{
    public static class MeshIO
    {
        /// <summary>
        /// Load mesh from OBJ file.
        /// </summary>
        public static bool LoadOBJ(string filename, out Vector3[] vertices, out int[,] faces)
        {
            vertices = Array.Empty<Vector3>();
            faces = new int[0, 0];
            
            if (!File.Exists(filename))
            {
                Console.WriteLine($"File not found: {filename}");
                return false;
            }
            
            var vertList = new List<Vector3>();
            var faceList = new List<int[]>();
            
            foreach (var line in File.ReadLines(filename))
            {
                var parts = line.Split(new[] { ' ' }, StringSplitOptions.RemoveEmptyEntries);
                if (parts.Length == 0) continue;
                
                if (parts[0] == "v" && parts.Length >= 4)
                {
                    // Vertex
                    float x = float.Parse(parts[1]);
                    float y = float.Parse(parts[2]);
                    float z = float.Parse(parts[3]);
                    vertList.Add(new Vector3(x, y, z));
                }
                else if (parts[0] == "f" && parts.Length >= 4)
                {
                    // Face (assuming triangulated, 1-indexed)
                    int v1 = int.Parse(parts[1].Split('/')[0]) - 1;
                    int v2 = int.Parse(parts[2].Split('/')[0]) - 1;
                    int v3 = int.Parse(parts[3].Split('/')[0]) - 1;
                    faceList.Add(new[] { v1, v2, v3 });
                }
            }
            
            // Convert to arrays
            vertices = vertList.ToArray();
            faces = new int[faceList.Count, 3];
            for (int i = 0; i < faceList.Count; i++)
            {
                faces[i, 0] = faceList[i][0];
                faces[i, 1] = faceList[i][1];
                faces[i, 2] = faceList[i][2];
            }
            
            Console.WriteLine($"Loaded {filename}: {vertices.Length} vertices, {faces.GetLength(0)} faces");
            return true;
        }
        
        /// <summary>
        /// Save mesh to OBJ file.
        /// </summary>
        public static bool SaveOBJ(string filename, Vector3[] vertices, int[,] faces)
        {
            try
            {
                using var writer = new StreamWriter(filename);
                
                writer.WriteLine("# OBJ file generated by DDG Course Companion");
                writer.WriteLine("# Added by Graph Technologies, 2025");
                writer.WriteLine($"# Vertices: {vertices.Length}, Faces: {faces.GetLength(0)}\n");
                
                // Write vertices
                foreach (var v in vertices)
                {
                    writer.WriteLine($"v {v.X} {v.Y} {v.Z}");
                }
                
                writer.WriteLine();
                
                // Write faces (convert to 1-indexed)
                for (int i = 0; i < faces.GetLength(0); i++)
                {
                    writer.WriteLine($"f {faces[i,0] + 1} {faces[i,1] + 1} {faces[i,2] + 1}");
                }
                
                Console.WriteLine($"Saved {filename}");
                return true;
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error saving file: {ex.Message}");
                return false;
            }
        }
        
        /// <summary>
        /// Load mesh directly into Mesh object.
        /// </summary>
        public static bool LoadMesh(string filename, Mesh mesh)
        {
            if (!LoadOBJ(filename, out var vertices, out var faces))
                return false;
            
            mesh.Build(vertices, faces);
            return true;
        }
        
        /// <summary>
        /// Save mesh from Mesh object.
        /// </summary>
        public static bool SaveMesh(string filename, Mesh mesh)
        {
            var vertices = mesh.GetPositions();
            
            // Build face array
            var faces = new int[mesh.Faces.Count, 3];
            for (int i = 0; i < mesh.Faces.Count; i++)
            {
                var verts = mesh.Faces[i].Vertices();
                faces[i, 0] = verts[0].Index;
                faces[i, 1] = verts[1].Index;
                faces[i, 2] = verts[2].Index;
            }
            
            return SaveOBJ(filename, vertices, faces);
        }
    }
}
