// MeshIO.cpp
// Mesh I/O implementation
// Added by Graph Technologies, 2025

#include "MeshIO.h"
#include <fstream>
#include <sstream>
#include <iostream>

namespace ddg {
namespace io {

bool MeshIO::loadOBJ(const std::string& filename,
                     Eigen::MatrixXd& V,
                     Eigen::MatrixXi& F) {
    std::ifstream file(filename);
    if (!file.is_open()) {
        std::cerr << "Failed to open file: " << filename << std::endl;
        return false;
    }
    
    std::vector<Eigen::Vector3d> vertices;
    std::vector<Eigen::Vector3i> faces;
    
    std::string line;
    while (std::getline(file, line)) {
        std::istringstream iss(line);
        std::string type;
        iss >> type;
        
        if (type == "v") {
            // Vertex
            double x, y, z;
            iss >> x >> y >> z;
            vertices.push_back(Eigen::Vector3d(x, y, z));
        }
        else if (type == "f") {
            // Face (assuming triangulated)
            int v1, v2, v3;
            iss >> v1 >> v2 >> v3;
            // OBJ indices are 1-based
            faces.push_back(Eigen::Vector3i(v1 - 1, v2 - 1, v3 - 1));
        }
    }
    
    // Convert to matrices
    V.resize(vertices.size(), 3);
    F.resize(faces.size(), 3);
    
    for (size_t i = 0; i < vertices.size(); i++) {
        V.row(i) = vertices[i];
    }
    
    for (size_t i = 0; i < faces.size(); i++) {
        F.row(i) = faces[i];
    }
    
    std::cout << "Loaded " << filename << ": "
              << V.rows() << " vertices, "
              << F.rows() << " faces" << std::endl;
    
    return true;
}

bool MeshIO::saveOBJ(const std::string& filename,
                     const Eigen::MatrixXd& V,
                     const Eigen::MatrixXi& F) {
    std::ofstream file(filename);
    if (!file.is_open()) {
        std::cerr << "Failed to open file for writing: " << filename << std::endl;
        return false;
    }
    
    // Write header
    file << "# OBJ file generated by DDG Course Companion\n";
    file << "# Added by Graph Technologies, 2025\n";
    file << "# Vertices: " << V.rows() << ", Faces: " << F.rows() << "\n\n";
    
    // Write vertices
    for (int i = 0; i < V.rows(); i++) {
        file << "v " << V(i, 0) << " " << V(i, 1) << " " << V(i, 2) << "\n";
    }
    
    file << "\n";
    
    // Write faces (1-indexed)
    for (int i = 0; i < F.rows(); i++) {
        file << "f " << (F(i, 0) + 1) << " " 
             << (F(i, 1) + 1) << " " 
             << (F(i, 2) + 1) << "\n";
    }
    
    std::cout << "Saved " << filename << std::endl;
    return true;
}

bool MeshIO::loadOFF(const std::string& filename,
                     Eigen::MatrixXd& V,
                     Eigen::MatrixXi& F) {
    std::ifstream file(filename);
    if (!file.is_open()) return false;
    
    std::string header;
    file >> header;
    if (header != "OFF") {
        std::cerr << "Not a valid OFF file" << std::endl;
        return false;
    }
    
    int nV, nF, nE;
    file >> nV >> nF >> nE;
    
    V.resize(nV, 3);
    F.resize(nF, 3);
    
    // Read vertices
    for (int i = 0; i < nV; i++) {
        file >> V(i, 0) >> V(i, 1) >> V(i, 2);
    }
    
    // Read faces
    for (int i = 0; i < nF; i++) {
        int n;
        file >> n;
        if (n != 3) {
            std::cerr << "Only triangular meshes supported" << std::endl;
            return false;
        }
        file >> F(i, 0) >> F(i, 1) >> F(i, 2);
    }
    
    std::cout << "Loaded OFF: " << nV << " vertices, " << nF << " faces" << std::endl;
    return true;
}

bool MeshIO::saveOFF(const std::string& filename,
                     const Eigen::MatrixXd& V,
                     const Eigen::MatrixXi& F) {
    std::ofstream file(filename);
    if (!file.is_open()) return false;
    
    file << "OFF\n";
    file << V.rows() << " " << F.rows() << " 0\n";
    
    for (int i = 0; i < V.rows(); i++) {
        file << V(i, 0) << " " << V(i, 1) << " " << V(i, 2) << "\n";
    }
    
    for (int i = 0; i < F.rows(); i++) {
        file << "3 " << F(i, 0) << " " << F(i, 1) << " " << F(i, 2) << "\n";
    }
    
    std::cout << "Saved OFF: " << filename << std::endl;
    return true;
}

bool MeshIO::loadMesh(const std::string& filename, Mesh& mesh) {
    Eigen::MatrixXd V;
    Eigen::MatrixXi F;
    
    // Detect format by extension
    if (filename.substr(filename.length() - 4) == ".obj") {
        if (!loadOBJ(filename, V, F)) return false;
    } else if (filename.substr(filename.length() - 4) == ".off") {
        if (!loadOFF(filename, V, F)) return false;
    } else {
        std::cerr << "Unsupported file format" << std::endl;
        return false;
    }
    
    mesh.build(V, F);
    return true;
}

bool MeshIO::saveMesh(const std::string& filename, const Mesh& mesh) {
    Eigen::MatrixXd V = mesh.vertexPositions();
    
    // Build face matrix
    Eigen::MatrixXi F(mesh.numFaces(), 3);
    for (size_t i = 0; i < mesh.faces.size(); i++) {
        auto verts = mesh.faces[i]->vertices();
        F(i, 0) = verts[0]->index;
        F(i, 1) = verts[1]->index;
        F(i, 2) = verts[2]->index;
    }
    
    // Detect format and save
    if (filename.substr(filename.length() - 4) == ".obj") {
        return saveOBJ(filename, V, F);
    } else if (filename.substr(filename.length() - 4) == ".off") {
        return saveOFF(filename, V, F);
    }
    
    return false;
}

} // namespace io
} // namespace ddg
